---
abstract: 'Yet another approach to modernistic Perl'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300036, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Defaults-Modern
recommends:
  PerlX::Maybe::XS: 0.005
requires:
  Carp: 0
  Function::Parameters: 1.0201
  Import::Into: 1
  Keyword::Simple: 0
  List::Objects::Types: 0
  List::Objects::WithUtils: 1.009
  Path::Tiny: 0.03
  PerlX::Maybe: 0.004
  Scalar::Util: 0
  Try::Tiny: 0
  Type::Tiny: 0.022
  Types::Path::Tiny: 0.005
  bareword::filehandles: 0
  indirect: 0.30
  match::simple: 0.004
  perl: v5.14.1
  true: 0.18
resources:
  repository: git://github.com/avenj/defaults-modern.git
version: 0.003002
