---
abstract: 'Yet another approach to modernistic Perl'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Defaults-Modern
recommends:
  PerlX::Maybe::XS: 1
requires:
  Carp: 0
  Exporter::Tiny: 0.034
  Function::Parameters: 1.0301
  Import::Into: 1
  Keyword::Simple: 0
  List::Objects::Types: 1.002
  List::Objects::WithUtils: 2.008
  Module::Runtime: 0
  Moo: 1
  MooX::late: 0.014
  Path::Tiny: 0.05
  PerlX::Maybe: 1
  Scalar::Util: 0
  Switch::Plain: 0
  Try::Tiny: 0
  Type::Tiny: 0.022
  Types::LoadableClass: 0.002
  Types::Path::Tiny: 0.005
  bareword::filehandles: 0
  indirect: 0.30
  match::simple: 0.004
  perl: v5.14.1
  true: 0.18
resources:
  repository: git://github.com/avenj/defaults-modern.git
version: 0.007002
